name: 🚀 Feature Request
description: I have a suggestion (and may want to implement it 🙂)!
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: checkboxes
    attributes:
      label: First, a few things...
      description: This will help us better interpret your request.
      options:
        - label: Is your feature request related to a problem?
          required: false
        - label: Will this feature just help you or is it something everyone needs?
          required: false
        - label: Have you tried to implement or draft this feature?
          required: false
        - label: Is your feature a breaking change?
          required: false
  - type: textarea
    attributes:
      label: 😄 Describe the solution you'd like
      description: A clear and concise description of what you want to happen in the mod. Add any considered drawbacks.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🧠 Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered for the mod.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🤚 Drawbacks
      description: Describe any potential drawbacks or challenges associated with this feature.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ✍️ Additional context
      description: |
        Any additional information, links, or references that provide more context about your feature request.
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
