package kamkeel.npcdbc.network.packets;

public enum EnumPacketPlayer {
    AuraList,
    AuraSelect,
    AuraSet,
    EffectList,
    FormList,
    FormWheel,
    FormWheelSave,
    FormSelect,
    OutlineList,
    Flight,
    SetVal,
    LockOnUpdate,
    LockOnSync,
    LoginInfo,
    PingPacket,
    PingFormColorPacket,
    PlaySound,
    FormSaveCustiomization,
    SendChat,
    StopSound,
    Transform,
    NPCPingForm,
    CustomSkill,
    Turbo,
    AbilitySelect,
    AbilityToggle
}
