package kamkeel.npcdbc.network.packets;

public enum EnumPacketPlayer {
    AuraList,
    AuraSelect,
    AuraSet,
    EffectList,
    FormList,
    FormWheel,
    FormWheelSave,
    FormSelect,
    AbilityList,
    AbilityWheel,
    AbilityWheelSave,
    AbilitySelect,
    OutlineList,
    Flight,
    SetVal,
    LockOn,
    LoginInfo,
    PingPacket,
    PingFormColorPacket,
    PlaySound,
    FormSaveCustiomization,
    SendChat,
    StopSound,
    Transform,
    AbilityUse,
    AbilityAnimate,
    NPCPingForm, Turbo
}
